actors:
  doi:
    image_url: /images/actors/doi.jpg
    name: 土井
    url: http://sns.example.com/alice
  peipeipe:
    image_url: /images/actors/peipeipe.jpg
    name: peipeipe
    url: https://www.peipeipe.net/
author: alice
description: WWWでつかまえます。
description_long: インターネットが大好きな2人が最近あったことを話します。やらなくちゃいけないことがたくさんある世の中を生き抜いていく。
email: www-de-tsukamaete@googlegroups.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: wtsuka
itunes_podcast_url: https://www-de-tsukamaete.github.io/feed.xml
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: WWWでつかまえて
url: https://www-de-tsukamaete.github.io/
